version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/CryptocurrencyTracker
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 60
      runas: root

