version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/CryptocurrencyTracker
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server
      timeout: 60
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 60
      runas: ec2-user
